(ns pokemon.components
  (:require
   [pokemon.routes :refer [path-for]]
   [pokemon.util :refer [set-theme!]]))

(defn poke-store-type
  [poketype]
  [:a.poketype-link
   {:style {:background-color (str "var(--" poketype ")")}
    :href (path-for (-> poketype keyword))
    :key poketype
    :on-click (set-theme! poketype)}
   poketype])

(defn nav
  []
  [:nav
   [:ul
    [:li {:name "home"
          :on-click (set-theme! "home")}
     [:a {:href (path-for :index)} "Home"]]
    [:li {:on-click (set-theme! "about")}
     [:a {:href (path-for :about)} "About pokemon"]]]])

(defn footer
  []
  [:footer
   [:p "pokemon was generated by the "
    [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]])
