(ns pokemon.pages
  (:require
   [reagent.session :as session]
   [pokemon.store :refer [store]]
   [pokemon.util :refer [set-theme!]]
   [pokemon.components :refer [poke-store-type
                               path-for]]))

(defn home-page []
  (fn []
    [:section
     [:h1 "Escolha sua loja de pokemon"]
     [:ul.poketype-list
      (->> @store :types (map poke-store-type))]]))

(defn items-page []
  (fn []
    [:span
     [:h1 "The items of pokemon"]
     [:ul.item-list (map (fn [item-id]
                           [:li.item {:name (str "item-" item-id)
                                      :key (str "item-" item-id)}
                            [:a {:href (path-for :item {:item-id item-id})} "Item: " item-id]])
                         (range 1 60))]]))

(defn item-page []
  (fn []
    (let [routing-data (session/get :route)
          item (get-in routing-data [:route-params :item-id])]
      [:span
       [:h1 (str "Item " item " of pokemon")]
       [:p [:a {:href (path-for :items)} "Back to the list of items"]]])))

(defn about-page []
  (fn [] [:span
          [:h1 "About pokemon"]]))

(defn current-page
  "Page mounting component"
  []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:main.main
       [:nav
        [:ul
         [:li {:name "home"
               :on-click (set-theme! "home")}
          [:a {:href (path-for :index)} "Home"]]
         [:li {:on-click (set-theme! "about")}
          [:a {:href (path-for :about)} "About pokemon"]]]]

       [page]
       [:footer
        [:p "pokemon was generated by the "
         [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]])))

(defn page-for [route]
  (case route
    :index #'home-page
    :about #'about-page
    :items #'items-page
    (:normal :fighting :flying :poison
             :ground :rock :bug :ghost
             :steel :fire :water :grass
             :electric :psychic :ice :dragon
             :dark :fairy :unknown :shadow) #'items-page
    :item #'item-page))
