(ns pokemon.pages
  (:require
   [reagent.session :as session]
   [pokemon.store :refer [store]]
   [pokemon.util :refer [set-theme!]]
   [pokemon.routes :refer [path-for]]
   [pokemon.components :refer [poke-store-type]]))

(defn home-page []
  (fn []
    [:section
     [:h1 "Escolha sua loja de pokemon"]
     [:ul.poketype-list
      (->> @store :types (map poke-store-type))]]))

(defn items-page []
  (fn []
    (let [current-page (-> @store :select-store)]
      [:span
       [:h1 "The items of pokemon"]
       [:ul.item-list (map (fn [poke-id]
                             [:li.item {:name (str current-page "-" poke-id)
                                        :key (str current-page "-" poke-id)}
                              [:a {:href (path-for
                                          (-> (str current-page "-" "poke") keyword)
                                          {:poke-id poke-id})}
                               "Item: " poke-id]])
                           (range 1 60))]])))

(defn item-page []
  (fn []
    (let [routing-data (session/get :route)
          item (get-in routing-data [:route-params :poke-id])]
      [:span
       [:h1 (str "Item " item " of pokemon")]
       [:p [:a {:href (path-for :index)} "Back to the list of items"]]])))

(defn about-page []
  (fn [] [:span
          [:h1 "About pokemon"]]))

(defn current-page
  "Page mounting component"
  []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:main.main
       [:nav
        [:ul
         [:li {:name "home"
               :on-click (set-theme! "home")}
          [:a {:href (path-for :index)} "Home"]]
         [:li {:on-click (set-theme! "about")}
          [:a {:href (path-for :about)} "About pokemon"]]]]

       [page]
       [:footer
        [:p "pokemon was generated by the "
         [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]])))

(defn page-for [route]
  (case route
    :index home-page
    :about about-page
    (:normal
     :fighting
     :flying
     :poison
     :ground
     :rock
     :bug
     :ghost
     :steel
     :fire
     :water
     :grass
     :electric
     :psychic
     :ice
     :dragon
     :dark
     :fairy
     :unknown
     :shadow) items-page
    (:normal-poke
     :fighting-poke
     :flying-poke
     :poison-poke
     :ground-poke
     :rock-poke
     :bug-poke
     :ghost-poke
     :steel-poke
     :fire-poke
     :water-poke
     :grass-poke
     :electric-poke
     :psychic-poke
     :ice-poke
     :dragon-poke
     :dark-poke
     :fairy-poke
     :unknown-poke
     :shadow-poke) item-page))
